import { Node, Edge } from '@xyflow/react';

export function generateCpp(nodes: Node[], edges: Edge[]) {
  let code = `// C++ Reverb generated by Audio Graph Model\n`;
  code += `#pragma once\n#include <vector>\n#include <cmath>\n\n`;
  
  code += `class AudioProcessor {\n`;
  code += `public:\n`;
  code += `    AudioProcessor(float sampleRate = 44100.0f) : m_sampleRate(sampleRate) {\n`;
  code += `        init();\n`;
  code += `    }\n\n`;
  
  code += `    void init() {\n`;
  for (const node of nodes) {
     if (['delay', 'comb', 'allpass', 'modDelay'].includes(node.type || '')) {
         code += `        m_${node.id}_bufferL.resize((size_t)(m_sampleRate * 2.0f), 0.0f);\n`;
         code += `        m_${node.id}_bufferR.resize((size_t)(m_sampleRate * 2.0f), 0.0f);\n`;
     }
  }
  code += `    }\n\n`;
  
  code += `    void processBlock(const float* inL, const float* inR, float* outL, float* outR, int numSamples) {\n`;
  code += `        for (int i = 0; i < numSamples; ++i) {\n`;
  code += `            // 1. Read Inputs\n`;
  
  // Very simplistic representation
  for (const node of nodes) {
      if (node.id === 'in') continue;
      if (node.id === 'out') continue;
      code += `            float ${node.id}_inL = 0.0f;\n`;
      code += `            float ${node.id}_inR = 0.0f;\n`;
  }
  
  code += `\n            // 2. Process Nodes (Skeleton representation)\n`;
  for (const node of nodes) {
      if (node.id === 'in' || node.id === 'out') continue;
      code += `            float ${node.id}_outL = ${node.id}_inL;\n`;
      code += `            float ${node.id}_outR = ${node.id}_inR;\n`;
      if (node.data?.params) {
          code += `            // parameters: \n`;
          for (const [k, v] of Object.entries(node.data.params)) {
             code += `            //   ${k} = ${(v as any).value}\n`;
          }
      }
  }

  code += `\n            // 3. Output\n`;
  code += `            outL[i] = inL[i]; // Placeholder out\n`;
  code += `            outR[i] = inR[i]; // Placeholder out\n`;
  
  code += `        }\n`;
  code += `    }\n\n`;
  
  code += `private:\n`;
  code += `    float m_sampleRate;\n`;
  for (const node of nodes) {
     if (['delay', 'comb', 'allpass', 'modDelay'].includes(node.type || '')) {
        code += `    std::vector<float> m_${node.id}_bufferL;\n`;
        code += `    std::vector<float> m_${node.id}_bufferR;\n`;
        code += `    int m_${node.id}_ptr = 0;\n`;
     }
  }
  
  code += `};\n`;
  return code;
}
