export function exportToCpp(nodes: any[], edges: any[]) {
  let code = `// Auto-generated by Reverb DSP Factory
#include <vector>
#include <cmath>
#include <iostream>
#include <algorithm>

class CustomReverb {
public:
    CustomReverb(float sampleRate) : sampleRate(sampleRate) {
        init();
    }

    void init() {
`;

  // Initialize buffers
  nodes.forEach(n => {
     if (['delay', 'allpass', 'comb', 'pitchShift', 'modDelay'].includes(n.type)) {
         code += `        bufL_${n.id}.resize(sampleRate * 2.0f, 0.0f);\n`;
         code += `        bufR_${n.id}.resize(sampleRate * 2.0f, 0.0f);\n`;
         code += `        ptr_${n.id} = 0;\n`;
     }
     if (['lpf', 'hpf', 'comb'].includes(n.type)) {
         code += `        z1L_${n.id} = 0.0f;\n`;
         code += `        z1R_${n.id} = 0.0f;\n`;
     }
     if (n.type === 'biquad') {
         code += `        x1L_${n.id} = 0.0f; x2L_${n.id} = 0.0f; y1L_${n.id} = 0.0f; y2L_${n.id} = 0.0f;\n`;
         code += `        x1R_${n.id} = 0.0f; x2R_${n.id} = 0.0f; y1R_${n.id} = 0.0f; y2R_${n.id} = 0.0f;\n`;
     }
     if (n.type === 'pitchShift' || n.type === 'lfo') {
         code += `        phase_${n.id} = 0.0f;\n`;
     }
     if (n.type === 'clamp') {
         code += `        env_${n.id} = 0.0f;\n`;
     }
  });

  code += `    }

    void processSample(float inputL, float inputR, float& outputL, float& outputR) {
`;

  // Declare variables
  nodes.forEach(n => {
      const numInputs = n.data.inputs !== undefined ? n.data.inputs : 1;
      if (numInputs === 0) {
          // No inputs
      } else if (numInputs === 1) {
          code += `        float inL_${n.id} = 0.0f;\n`;
          code += `        float inR_${n.id} = 0.0f;\n`;
      } else {
          for(let i=1; i<=numInputs; i++) {
              code += `        float inL_${i}_${n.id} = 0.0f;\n`;
              code += `        float inR_${i}_${n.id} = 0.0f;\n`;
          }
      }
      code += `        float outL_${n.id} = 0.0f;\n`;
      code += `        float outR_${n.id} = 0.0f;\n`;
  });

  code += `\n        // --- Input ---\n`;
  const inNode = nodes.find(n => n.type === 'audioIn');
  if (inNode) {
    code += `        inL_${inNode.id} = inputL;\n`;
    code += `        inR_${inNode.id} = inputR;\n`;
  }

  code += `\n        // --- Routing (Feedback loops have 1 sample delay) ---\n`;
  edges.forEach(e => {
      const sHandle = e.sourceHandle || 'out-both';
      const tHandle = e.targetHandle || 'in-both';
      
      let valL = `last_outL_${e.source}`;
      let valR = `last_outR_${e.source}`;
      
      let sParts = sHandle.split('-');
      if (sParts.length === 3) {
          let sIdx = sParts[1];
          valL = `last_outL_${sIdx}_${e.source}`;
          valR = `last_outR_${sIdx}_${e.source}`;
      }
      
      if (sHandle.endsWith('-l')) valR = '0.0f';
      if (sHandle.endsWith('-r')) valL = '0.0f';
      
      let targetVarL = `inL_${e.target}`;
      let targetVarR = `inR_${e.target}`;
      
      if (tHandle.startsWith('in-') && tHandle.split('-').length === 3) {
          let idx = tHandle.split('-')[1];
          targetVarL = `inL_${idx}_${e.target}`;
          targetVarR = `inR_${idx}_${e.target}`;
      }
      
      if (tHandle.endsWith('-l')) {
          code += `        ${targetVarL} += ${valL};\n`;
      } else if (tHandle.endsWith('-r')) {
          code += `        ${targetVarR} += ${valR};\n`;
      } else {
          code += `        ${targetVarL} += ${valL};\n`;
          code += `        ${targetVarR} += ${valR};\n`;
      }
  });

  code += `\n        // --- DSP Processing ---\n`;
  nodes.forEach(n => {
      const params = n.data.params || {};
      
      if (n.type === 'audioIn') {
          code += `        outL_${n.id} = inL_${n.id};\n`;
          code += `        outR_${n.id} = inR_${n.id};\n`;
      } else if (n.type === 'biquad') {
          const filterType = params.filterType?.value || 0;
          const freq = params.freq?.value || 1000;
          const Q = params.q?.value || 0.707;
          const dbGain = params.gain?.value || 0;
          code += `        float filterType_${n.id} = ${filterType};\n`;
          code += `        float freq_${n.id} = ${freq}f;\n`;
          code += `        float Q_${n.id} = ${Q}f;\n`;
          code += `        float dbGain_${n.id} = ${dbGain}f;\n`;
          code += `        float A_${n.id} = powf(10.0f, dbGain_${n.id} / 40.0f);\n`;
          code += `        float w0_${n.id} = 2.0f * M_PI * freq_${n.id} / sampleRate;\n`;
          code += `        float alpha_${n.id} = sinf(w0_${n.id}) / (2.0f * Q_${n.id});\n`;
          code += `        float cosW0_${n.id} = cosf(w0_${n.id});\n`;
          code += `        float b0_${n.id}=1.0f, b1_${n.id}=0.0f, b2_${n.id}=0.0f, a0_${n.id}=1.0f, a1_${n.id}=0.0f, a2_${n.id}=0.0f;\n`;
          code += `        if (filterType_${n.id} == 0) {\n`;
          code += `            b0_${n.id} = (1.0f - cosW0_${n.id}) / 2.0f; b1_${n.id} = 1.0f - cosW0_${n.id}; b2_${n.id} = (1.0f - cosW0_${n.id}) / 2.0f;\n`;
          code += `            a0_${n.id} = 1.0f + alpha_${n.id}; a1_${n.id} = -2.0f * cosW0_${n.id}; a2_${n.id} = 1.0f - alpha_${n.id};\n`;
          code += `        } else if (filterType_${n.id} == 1) {\n`;
          code += `            b0_${n.id} = (1.0f + cosW0_${n.id}) / 2.0f; b1_${n.id} = -(1.0f + cosW0_${n.id}); b2_${n.id} = (1.0f + cosW0_${n.id}) / 2.0f;\n`;
          code += `            a0_${n.id} = 1.0f + alpha_${n.id}; a1_${n.id} = -2.0f * cosW0_${n.id}; a2_${n.id} = 1.0f - alpha_${n.id};\n`;
          code += `        } else if (filterType_${n.id} == 2) {\n`;
          code += `            b0_${n.id} = alpha_${n.id}; b1_${n.id} = 0.0f; b2_${n.id} = -alpha_${n.id};\n`;
          code += `            a0_${n.id} = 1.0f + alpha_${n.id}; a1_${n.id} = -2.0f * cosW0_${n.id}; a2_${n.id} = 1.0f - alpha_${n.id};\n`;
          code += `        } else if (filterType_${n.id} == 3) {\n`;
          code += `            b0_${n.id} = A_${n.id} * ((A_${n.id} + 1) - (A_${n.id} - 1) * cosW0_${n.id} + 2 * sqrtf(A_${n.id}) * alpha_${n.id});\n`;
          code += `            b1_${n.id} = 2.0 * A_${n.id} * ((A_${n.id} - 1) - (A_${n.id} + 1) * cosW0_${n.id});\n`;
          code += `            b2_${n.id} = A_${n.id} * ((A_${n.id} + 1) - (A_${n.id} - 1) * cosW0_${n.id} - 2 * sqrtf(A_${n.id}) * alpha_${n.id});\n`;
          code += `            a0_${n.id} = (A_${n.id} + 1) + (A_${n.id} - 1) * cosW0_${n.id} + 2 * sqrtf(A_${n.id}) * alpha_${n.id};\n`;
          code += `            a1_${n.id} = -2.0 * ((A_${n.id} - 1) + (A_${n.id} + 1) * cosW0_${n.id});\n`;
          code += `            a2_${n.id} = (A_${n.id} + 1) + (A_${n.id} - 1) * cosW0_${n.id} - 2 * sqrtf(A_${n.id}) * alpha_${n.id};\n`;
          code += `        } else if (filterType_${n.id} == 4) {\n`;
          code += `            b0_${n.id} = A_${n.id} * ((A_${n.id} + 1) + (A_${n.id} - 1) * cosW0_${n.id} + 2 * sqrtf(A_${n.id}) * alpha_${n.id});\n`;
          code += `            b1_${n.id} = -2.0 * A_${n.id} * ((A_${n.id} - 1) + (A_${n.id} + 1) * cosW0_${n.id});\n`;
          code += `            b2_${n.id} = A_${n.id} * ((A_${n.id} + 1) + (A_${n.id} - 1) * cosW0_${n.id} - 2 * sqrtf(A_${n.id}) * alpha_${n.id});\n`;
          code += `            a0_${n.id} = (A_${n.id} + 1) - (A_${n.id} - 1) * cosW0_${n.id} + 2 * sqrtf(A_${n.id}) * alpha_${n.id};\n`;
          code += `            a1_${n.id} = 2.0 * ((A_${n.id} - 1) - (A_${n.id} + 1) * cosW0_${n.id});\n`;
          code += `            a2_${n.id} = (A_${n.id} + 1) - (A_${n.id} - 1) * cosW0_${n.id} - 2 * sqrtf(A_${n.id}) * alpha_${n.id};\n`;
          code += `        } else if (filterType_${n.id} == 5) {\n`;
          code += `            b0_${n.id} = 1.0f + alpha_${n.id} * A_${n.id}; b1_${n.id} = -2.0f * cosW0_${n.id}; b2_${n.id} = 1.0f - alpha_${n.id} * A_${n.id};\n`;
          code += `            a0_${n.id} = 1.0f + alpha_${n.id} / A_${n.id}; a1_${n.id} = -2.0f * cosW0_${n.id}; a2_${n.id} = 1.0f - alpha_${n.id} / A_${n.id};\n`;
          code += `        } else if (filterType_${n.id} == 6) {\n`;
          code += `            b0_${n.id} = 1.0f; b1_${n.id} = -2.0f * cosW0_${n.id}; b2_${n.id} = 1.0f;\n`;
          code += `            a0_${n.id} = 1.0f + alpha_${n.id}; a1_${n.id} = -2.0f * cosW0_${n.id}; a2_${n.id} = 1.0f - alpha_${n.id};\n`;
          code += `        }\n`;
          code += `        outL_${n.id} = (b0_${n.id} / a0_${n.id}) * inL_${n.id} + (b1_${n.id} / a0_${n.id}) * x1L_${n.id} + (b2_${n.id} / a0_${n.id}) * x2L_${n.id} - (a1_${n.id} / a0_${n.id}) * y1L_${n.id} - (a2_${n.id} / a0_${n.id}) * y2L_${n.id};\n`;
          code += `        x2L_${n.id} = x1L_${n.id}; x1L_${n.id} = inL_${n.id}; y2L_${n.id} = y1L_${n.id}; y1L_${n.id} = outL_${n.id};\n`;
          code += `        outR_${n.id} = (b0_${n.id} / a0_${n.id}) * inR_${n.id} + (b1_${n.id} / a0_${n.id}) * x1R_${n.id} + (b2_${n.id} / a0_${n.id}) * x2R_${n.id} - (a1_${n.id} / a0_${n.id}) * y1R_${n.id} - (a2_${n.id} / a0_${n.id}) * y2R_${n.id};\n`;
          code += `        x2R_${n.id} = x1R_${n.id}; x1R_${n.id} = inR_${n.id}; y2R_${n.id} = y1R_${n.id}; y1R_${n.id} = outR_${n.id};\n`;
      } else if (n.type === 'lfo') {
          const rate = params.rate?.value || 1.0;
          const depth = params.depth?.value || 1.0;
          code += `        phase_${n.id} += ${rate}f / sampleRate;\n`;
          code += `        if (phase_${n.id} >= 1.0f) phase_${n.id} -= 1.0f;\n`;
          code += `        outL_${n.id} = sinf(phase_${n.id} * 2.0f * M_PI) * ${depth}f;\n`;
          code += `        outR_${n.id} = outL_${n.id};\n`;
      } else if (n.type === 'fdn4') {
          code += `        outL_1_${n.id} = 0.5f * (inL_1_${n.id} + inL_2_${n.id} + inL_3_${n.id} + inL_4_${n.id});\n`;
          code += `        outL_2_${n.id} = 0.5f * (inL_1_${n.id} - inL_2_${n.id} + inL_3_${n.id} - inL_4_${n.id});\n`;
          code += `        outL_3_${n.id} = 0.5f * (inL_1_${n.id} + inL_2_${n.id} - inL_3_${n.id} - inL_4_${n.id});\n`;
          code += `        outL_4_${n.id} = 0.5f * (inL_1_${n.id} - inL_2_${n.id} - inL_3_${n.id} + inL_4_${n.id});\n`;
          code += `        outR_1_${n.id} = 0.5f * (inR_1_${n.id} + inR_2_${n.id} + inR_3_${n.id} + inR_4_${n.id});\n`;
          code += `        outR_2_${n.id} = 0.5f * (inR_1_${n.id} - inR_2_${n.id} + inR_3_${n.id} - inR_4_${n.id});\n`;
          code += `        outR_3_${n.id} = 0.5f * (inR_1_${n.id} + inR_2_${n.id} - inR_3_${n.id} - inR_4_${n.id});\n`;
          code += `        outR_4_${n.id} = 0.5f * (inR_1_${n.id} - inR_2_${n.id} - inR_3_${n.id} + inR_4_${n.id});\n`;
          code += `        outL_${n.id} = outL_1_${n.id}; // default out\n`;
          code += `        outR_${n.id} = outR_1_${n.id};\n`;
      } else if (n.type === 'modDelay') {
          const delayMs = params.delayMs?.value || 20;
          const fb = params.feedback?.value || 0;
          code += `        float modSamplesL_${n.id} = (inL_2_${n.id} / 1000.0f) * sampleRate;\n`;
          code += `        float modSamplesR_${n.id} = (inR_2_${n.id} / 1000.0f) * sampleRate;\n`;
          code += `        float delaySamplesL_${n.id} = (${delayMs}f / 1000.0f) * sampleRate + modSamplesL_${n.id};\n`;
          code += `        float delaySamplesR_${n.id} = (${delayMs}f / 1000.0f) * sampleRate + modSamplesR_${n.id};\n`;
          code += `        if (delaySamplesL_${n.id} < 1.0f) delaySamplesL_${n.id} = 1.0f;\n`;
          code += `        if (delaySamplesR_${n.id} < 1.0f) delaySamplesR_${n.id} = 1.0f;\n`;
          code += `        if (delaySamplesL_${n.id} >= bufL_${n.id}.size()) delaySamplesL_${n.id} = bufL_${n.id}.size() - 1;\n`;
          code += `        if (delaySamplesR_${n.id} >= bufR_${n.id}.size()) delaySamplesR_${n.id} = bufR_${n.id}.size() - 1;\n`;
          code += `        float readPtrL_${n.id} = (float)ptr_${n.id} - delaySamplesL_${n.id};\n`;
          code += `        while (readPtrL_${n.id} < 0) readPtrL_${n.id} += bufL_${n.id}.size();\n`;
          code += `        int idxL1_${n.id} = (int)readPtrL_${n.id};\n`;
          code += `        int idxL2_${n.id} = (idxL1_${n.id} + 1) % bufL_${n.id}.size();\n`;
          code += `        float fracL_${n.id} = readPtrL_${n.id} - idxL1_${n.id};\n`;
          code += `        float delayedL_${n.id} = bufL_${n.id}[idxL1_${n.id}] * (1.0f - fracL_${n.id}) + bufL_${n.id}[idxL2_${n.id}] * fracL_${n.id};\n`;
          code += `        float readPtrR_${n.id} = (float)ptr_${n.id} - delaySamplesR_${n.id};\n`;
          code += `        while (readPtrR_${n.id} < 0) readPtrR_${n.id} += bufR_${n.id}.size();\n`;
          code += `        int idxR1_${n.id} = (int)readPtrR_${n.id};\n`;
          code += `        int idxR2_${n.id} = (idxR1_${n.id} + 1) % bufR_${n.id}.size();\n`;
          code += `        float fracR_${n.id} = readPtrR_${n.id} - idxR1_${n.id};\n`;
          code += `        float delayedR_${n.id} = bufR_${n.id}[idxR1_${n.id}] * (1.0f - fracR_${n.id}) + bufR_${n.id}[idxR2_${n.id}] * fracR_${n.id};\n`;
          code += `        outL_${n.id} = delayedL_${n.id};\n`;
          code += `        outR_${n.id} = delayedR_${n.id};\n`;
          code += `        bufL_${n.id}[ptr_${n.id}] = inL_1_${n.id} + delayedL_${n.id} * ${fb}f;\n`;
          code += `        bufR_${n.id}[ptr_${n.id}] = inR_1_${n.id} + delayedR_${n.id} * ${fb}f;\n`;
          code += `        ptr_${n.id} = (ptr_${n.id} + 1) % bufL_${n.id}.size();\n`;
      } else if (n.type === 'delay') {
          const delayMs = params.delayMs?.value || 50;
          const fb = params.feedback?.value || 0;
          code += `        int delaySamples_${n.id} = (int)((${delayMs}f / 1000.0f) * sampleRate);\n`;
          code += `        int readPtr_${n.id} = ptr_${n.id} - delaySamples_${n.id};\n`;
          code += `        if (readPtr_${n.id} < 0) readPtr_${n.id} += bufL_${n.id}.size();\n`;
          code += `        float delayedL_${n.id} = bufL_${n.id}[readPtr_${n.id}];\n`;
          code += `        float delayedR_${n.id} = bufR_${n.id}[readPtr_${n.id}];\n`;
          code += `        outL_${n.id} = delayedL_${n.id};\n`;
          code += `        outR_${n.id} = delayedR_${n.id};\n`;
          code += `        bufL_${n.id}[ptr_${n.id}] = inL_${n.id} + delayedL_${n.id} * ${fb}f;\n`;
          code += `        bufR_${n.id}[ptr_${n.id}] = inR_${n.id} + delayedR_${n.id} * ${fb}f;\n`;
          code += `        ptr_${n.id} = (ptr_${n.id} + 1) % bufL_${n.id}.size();\n`;
      } else if (n.type === 'allpass') {
          const delayMs = params.delayMs?.value || 5;
          const gain = params.gain?.value || 0.7;
          code += `        int delaySamples_${n.id} = (int)((${delayMs}f / 1000.0f) * sampleRate);\n`;
          code += `        int readPtr_${n.id} = ptr_${n.id} - delaySamples_${n.id};\n`;
          code += `        if (readPtr_${n.id} < 0) readPtr_${n.id} += bufL_${n.id}.size();\n`;
          code += `        float delayedL_${n.id} = bufL_${n.id}[readPtr_${n.id}];\n`;
          code += `        float delayedR_${n.id} = bufR_${n.id}[readPtr_${n.id}];\n`;
          code += `        outL_${n.id} = -${gain}f * inL_${n.id} + delayedL_${n.id};\n`;
          code += `        outR_${n.id} = -${gain}f * inR_${n.id} + delayedR_${n.id};\n`;
          code += `        bufL_${n.id}[ptr_${n.id}] = inL_${n.id} + ${gain}f * delayedL_${n.id};\n`;
          code += `        bufR_${n.id}[ptr_${n.id}] = inR_${n.id} + ${gain}f * delayedR_${n.id};\n`;
          code += `        ptr_${n.id} = (ptr_${n.id} + 1) % bufL_${n.id}.size();\n`;
      } else if (n.type === 'comb') {
          const delayMs = params.delayMs?.value || 30;
          const fb = params.feedback?.value || 0.8;
          const damp = params.damping?.value || 0.2;
          code += `        int delaySamples_${n.id} = (int)((${delayMs}f / 1000.0f) * sampleRate);\n`;
          code += `        int readPtr_${n.id} = ptr_${n.id} - delaySamples_${n.id};\n`;
          code += `        if (readPtr_${n.id} < 0) readPtr_${n.id} += bufL_${n.id}.size();\n`;
          code += `        float delayedL_${n.id} = bufL_${n.id}[readPtr_${n.id}];\n`;
          code += `        float delayedR_${n.id} = bufR_${n.id}[readPtr_${n.id}];\n`;
          code += `        z1L_${n.id} = delayedL_${n.id} * (1.0f - ${damp}f) + z1L_${n.id} * ${damp}f;\n`;
          code += `        z1R_${n.id} = delayedR_${n.id} * (1.0f - ${damp}f) + z1R_${n.id} * ${damp}f;\n`;
          code += `        outL_${n.id} = delayedL_${n.id};\n`;
          code += `        outR_${n.id} = delayedR_${n.id};\n`;
          code += `        bufL_${n.id}[ptr_${n.id}] = inL_${n.id} + z1L_${n.id} * ${fb}f;\n`;
          code += `        bufR_${n.id}[ptr_${n.id}] = inR_${n.id} + z1R_${n.id} * ${fb}f;\n`;
          code += `        ptr_${n.id} = (ptr_${n.id} + 1) % bufL_${n.id}.size();\n`;
      } else if (n.type === 'pitchShift') {
          const semitones = params.semitones?.value || 0;
          const windowMs = params.windowMs?.value || 50;
          const mix = params.mix?.value !== undefined ? params.mix.value : 1.0;
          code += `        float pitchRatio_${n.id} = powf(2.0f, ${semitones}f / 12.0f);\n`;
          code += `        float windowSamples_${n.id} = (${windowMs}f / 1000.0f) * sampleRate;\n`;
          code += `        float phaseInc_${n.id} = (1.0f - pitchRatio_${n.id}) / windowSamples_${n.id};\n`;
          code += `        phase_${n.id} += phaseInc_${n.id};\n`;
          code += `        if (phase_${n.id} >= 1.0f) phase_${n.id} -= 1.0f;\n`;
          code += `        if (phase_${n.id} < 0.0f) phase_${n.id} += 1.0f;\n`;
          code += `        float phase1_${n.id} = phase_${n.id};\n`;
          code += `        float phase2_${n.id} = fmodf(phase_${n.id} + 0.5f, 1.0f);\n`;
          code += `        float delay1_${n.id} = phase1_${n.id} * windowSamples_${n.id};\n`;
          code += `        float delay2_${n.id} = phase2_${n.id} * windowSamples_${n.id};\n`;
          code += `        bufL_${n.id}[ptr_${n.id}] = inL_${n.id};\n`;
          code += `        bufR_${n.id}[ptr_${n.id}] = inR_${n.id};\n`;
          code += `        int readPtr1_${n.id} = ptr_${n.id} - (int)delay1_${n.id};\n`;
          code += `        if (readPtr1_${n.id} < 0) readPtr1_${n.id} += bufL_${n.id}.size();\n`;
          code += `        int readPtr2_${n.id} = ptr_${n.id} - (int)delay2_${n.id};\n`;
          code += `        if (readPtr2_${n.id} < 0) readPtr2_${n.id} += bufL_${n.id}.size();\n`;
          code += `        float fade1_${n.id} = 1.0f - fabsf(phase1_${n.id} * 2.0f - 1.0f);\n`;
          code += `        float fade2_${n.id} = 1.0f - fabsf(phase2_${n.id} * 2.0f - 1.0f);\n`;
          code += `        float wetL_${n.id} = bufL_${n.id}[readPtr1_${n.id}] * fade1_${n.id} + bufL_${n.id}[readPtr2_${n.id}] * fade2_${n.id};\n`;
          code += `        float wetR_${n.id} = bufR_${n.id}[readPtr1_${n.id}] * fade1_${n.id} + bufR_${n.id}[readPtr2_${n.id}] * fade2_${n.id};\n`;
          code += `        outL_${n.id} = inL_${n.id} * (1.0f - ${mix}f) + wetL_${n.id} * ${mix}f;\n`;
          code += `        outR_${n.id} = inR_${n.id} * (1.0f - ${mix}f) + wetR_${n.id} * ${mix}f;\n`;
          code += `        ptr_${n.id} = (ptr_${n.id} + 1) % bufL_${n.id}.size();\n`;
      } else if (n.type === 'lpf') {
          const cutoff = params.cutoff?.value || 1000;
          code += `        float dt_${n.id} = 1.0f / sampleRate;\n`;
          code += `        float rc_${n.id} = 1.0f / (2.0f * M_PI * ${cutoff}f);\n`;
          code += `        float alpha_${n.id} = dt_${n.id} / (rc_${n.id} + dt_${n.id});\n`;
          code += `        outL_${n.id} = z1L_${n.id} + alpha_${n.id} * (inL_${n.id} - z1L_${n.id});\n`;
          code += `        outR_${n.id} = z1R_${n.id} + alpha_${n.id} * (inR_${n.id} - z1R_${n.id});\n`;
          code += `        z1L_${n.id} = outL_${n.id};\n`;
          code += `        z1R_${n.id} = outR_${n.id};\n`;
      } else if (n.type === 'hpf') {
          const cutoff = params.cutoff?.value || 100;
          code += `        float dt_${n.id} = 1.0f / sampleRate;\n`;
          code += `        float rc_${n.id} = 1.0f / (2.0f * M_PI * ${cutoff}f);\n`;
          code += `        float alpha_${n.id} = rc_${n.id} / (rc_${n.id} + dt_${n.id});\n`;
          code += `        outL_${n.id} = alpha_${n.id} * (z1L_${n.id} + inL_${n.id} - last_inL_${n.id});\n`;
          code += `        outR_${n.id} = alpha_${n.id} * (z1R_${n.id} + inR_${n.id} - last_inR_${n.id});\n`;
          code += `        z1L_${n.id} = outL_${n.id};\n`;
          code += `        z1R_${n.id} = outR_${n.id};\n`;
          code += `        last_inL_${n.id} = inL_${n.id};\n`;
          code += `        last_inR_${n.id} = inR_${n.id};\n`;
      } else if (n.type === 'clamp') {
          const mode = params.mode?.value !== undefined ? params.mode.value : 1;
          const threshold = params.threshold?.value !== undefined ? params.threshold.value : 1.0;
          const drive = params.drive?.value !== undefined ? params.drive.value : 1.0;
          code += `        float drivenL_${n.id} = inL_${n.id} * ${drive}f;\n`;
          code += `        float drivenR_${n.id} = inR_${n.id} * ${drive}f;\n`;
          if (mode === 0) { // Hard clip
              code += `        outL_${n.id} = std::max(-${threshold}f, std::min(drivenL_${n.id}, ${threshold}f));\n`;
              code += `        outR_${n.id} = std::max(-${threshold}f, std::min(drivenR_${n.id}, ${threshold}f));\n`;
          } else if (mode === 1) { // Soft clip
              code += `        outL_${n.id} = std::tanh(drivenL_${n.id} / ${threshold}f) * ${threshold}f;\n`;
              code += `        outR_${n.id} = std::tanh(drivenR_${n.id} / ${threshold}f) * ${threshold}f;\n`;
          } else if (mode === 2) { // Compressor
              code += `        float absSigL_${n.id} = std::abs(drivenL_${n.id});\n`;
              code += `        float absSigR_${n.id} = std::abs(drivenR_${n.id});\n`;
              code += `        float maxSig_${n.id} = std::max(absSigL_${n.id}, absSigR_${n.id});\n`;
              code += `        float attack_${n.id} = 0.01f;\n`;
              code += `        float release_${n.id} = 0.001f;\n`;
              code += `        env_${n.id} = (maxSig_${n.id} > env_${n.id}) ? env_${n.id} + attack_${n.id} * (maxSig_${n.id} - env_${n.id}) : env_${n.id} + release_${n.id} * (maxSig_${n.id} - env_${n.id});\n`;
              code += `        float gain_${n.id} = 1.0f;\n`;
              code += `        if (env_${n.id} > ${threshold}f) {\n`;
              code += `            float dbEnv_${n.id} = 20.0f * std::log10(env_${n.id});\n`;
              code += `            float dbThresh_${n.id} = 20.0f * std::log10(${threshold}f);\n`;
              code += `            float targetDb_${n.id} = dbThresh_${n.id} + (dbEnv_${n.id} - dbThresh_${n.id}) / 4.0f;\n`; // 4:1
              code += `            gain_${n.id} = std::pow(10.0f, (dbThresh_${n.id} - targetDb_${n.id}) / 20.0f);\n`;
              code += `        }\n`;
              code += `        outL_${n.id} = drivenL_${n.id} * gain_${n.id};\n`;
              code += `        outR_${n.id} = drivenR_${n.id} * gain_${n.id};\n`;
          }
      } else if (n.type === 'mixer') {
          const g1 = params.gain1?.value !== undefined ? params.gain1.value : 1.0;
          const g2 = params.gain2?.value !== undefined ? params.gain2.value : 1.0;
          const g3 = params.gain3?.value !== undefined ? params.gain3.value : 1.0;
          const g4 = params.gain4?.value !== undefined ? params.gain4.value : 1.0;
          const mG = params.masterGain?.value !== undefined ? params.masterGain.value : 1.0;
          code += `        outL_${n.id} = (inL_1_${n.id} * ${g1}f + inL_2_${n.id} * ${g2}f + inL_3_${n.id} * ${g3}f + inL_4_${n.id} * ${g4}f) * ${mG}f;\n`;
          code += `        outR_${n.id} = (inR_1_${n.id} * ${g1}f + inR_2_${n.id} * ${g2}f + inR_3_${n.id} * ${g3}f + inR_4_${n.id} * ${g4}f) * ${mG}f;\n`;
      } else if (n.type === 'latency') {
          code += `        outL_${n.id} = inL_${n.id};\n`;
          code += `        outR_${n.id} = inR_${n.id};\n`;
      } else if (n.type === 'audioOut') {
          const gain = params.gain?.value !== undefined ? params.gain.value : 1.0;
          const limiter = params.limiter?.value !== undefined ? params.limiter.value : 1;
          code += `        float scaledL_${n.id} = inL_${n.id} * ${gain}f;\n`;
          code += `        float scaledR_${n.id} = inR_${n.id} * ${gain}f;\n`;
          if (limiter === 1) {
              code += `        outL_${n.id} = std::tanh(scaledL_${n.id});\n`;
              code += `        outR_${n.id} = std::tanh(scaledR_${n.id});\n`;
          } else {
              code += `        outL_${n.id} = scaledL_${n.id};\n`;
              code += `        outR_${n.id} = scaledR_${n.id};\n`;
          }
      }
  });

  code += `\n        // --- Update State ---\n`;
  nodes.forEach(n => {
      code += `        last_outL_${n.id} = outL_${n.id};\n`;
      code += `        last_outR_${n.id} = outR_${n.id};\n`;
      const numOutputs = n.data.outputs !== undefined ? n.data.outputs : 1;
      if (numOutputs > 1) {
          for(let i=1; i<=numOutputs; i++) {
              code += `        last_outL_${i}_${n.id} = outL_${i}_${n.id};\n`;
              code += `        last_outR_${i}_${n.id} = outR_${i}_${n.id};\n`;
          }
      }
  });

  const outNode = nodes.find(n => n.type === 'audioOut');
  if (outNode) {
    code += `\n        outputL = outL_${outNode.id};\n`;
    code += `        outputR = outR_${outNode.id};\n`;
  } else {
    code += `\n        outputL = 0.0f;\n`;
    code += `        outputR = 0.0f;\n`;
  }

  code += `    }\n\nprivate:\n    float sampleRate;\n`;
  
  // Declare state variables
  nodes.forEach(n => {
     const numOutputs = n.data.outputs !== undefined ? n.data.outputs : 1;
     code += `    float last_outL_${n.id} = 0.0f;\n`;
     code += `    float last_outR_${n.id} = 0.0f;\n`;
     if (numOutputs > 1) {
         for(let i=1; i<=numOutputs; i++) {
             code += `    float last_outL_${i}_${n.id} = 0.0f;\n`;
             code += `    float last_outR_${i}_${n.id} = 0.0f;\n`;
         }
     }
     if (['delay', 'allpass', 'comb', 'pitchShift', 'modDelay'].includes(n.type)) {
         code += `    std::vector<float> bufL_${n.id};\n`;
         code += `    std::vector<float> bufR_${n.id};\n`;
         code += `    int ptr_${n.id} = 0;\n`;
     }
     if (['lpf', 'hpf'].includes(n.type)) {
         code += `    float z1L_${n.id} = 0.0f;\n`;
         code += `    float z1R_${n.id} = 0.0f;\n`;
     }
     if (n.type === 'biquad') {
         code += `    float x1L_${n.id} = 0.0f, x2L_${n.id} = 0.0f, y1L_${n.id} = 0.0f, y2L_${n.id} = 0.0f;\n`;
         code += `    float x1R_${n.id} = 0.0f, x2R_${n.id} = 0.0f, y1R_${n.id} = 0.0f, y2R_${n.id} = 0.0f;\n`;
     }
     if (n.type === 'comb') {
         code += `    float z1L_${n.id} = 0.0f;\n`;
         code += `    float z1R_${n.id} = 0.0f;\n`;
     }
     if (n.type === 'hpf') {
         code += `    float last_inL_${n.id} = 0.0f;\n`;
         code += `    float last_inR_${n.id} = 0.0f;\n`;
     }
     if (n.type === 'pitchShift' || n.type === 'lfo') {
         code += `    float phase_${n.id} = 0.0f;\n`;
     }
     if (n.type === 'clamp') {
         code += `    float env_${n.id} = 0.0f;\n`;
     }
  });

  code += `};\n`;
  return code;
}
